/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Slan3D (https://sketchfab.com/slan3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glass-table-052afb862e7d4d50bc091cd7019f8b6f
Title: Glass Table
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
  };
  materials: {
    Piano_vetro: THREE.MeshStandardMaterial;
    Piedi: THREE.MeshStandardMaterial;
    Sostegni: THREE.MeshStandardMaterial;
  };
};

export function GlassTable(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/glass_table.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Piano_vetro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Piedi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Sostegni}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/glass_table.glb");
