/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WwWuengy (https://sketchfab.com/wwwuengy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-purple-glass-table-f6fa6d24e2424b9695f13866dfb6b4ce
Title: Modern Purple Glass Table
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
  };
  materials: {
    ["Color-metal"]: THREE.MeshPhysicalMaterial;
    ["black-Glass"]: THREE.MeshStandardMaterial;
    ["Metal-legs"]: THREE.MeshStandardMaterial;
    Rubber: THREE.MeshStandardMaterial;
  };
};

export function ModernTable(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/modern_table.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials["Color-metal"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials["black-Glass"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials["Metal-legs"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials["Color-metal"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials["Color-metal"]}
      />
    </group>
  );
}

useGLTF.preload("./models/modern_table.glb");
