/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mohamedhussien (https://sketchfab.com/mohamedhussien)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/round-wooden-table-01-4k-29f674147c784fe182839ae141156f3f
Title: Round Wooden Table 01 4k
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    round_wooden_table_01_round_wooden_table_01_0: THREE.Mesh;
    round_wooden_table_01_bolts_round_wooden_table_01_0: THREE.Mesh;
  };
  materials: {
    round_wooden_table_01: THREE.MeshStandardMaterial;
  };
};

export function RoundWoodTable(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/round_wooden_table.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.round_wooden_table_01_round_wooden_table_01_0.geometry
          }
          material={materials.round_wooden_table_01}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.round_wooden_table_01_bolts_round_wooden_table_01_0.geometry
          }
          material={materials.round_wooden_table_01}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/round_wooden_table.glb");
