/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-tv-shelf-210cm-290cbf357b3045e591ce58e64e66b41c
Title: Simple TV Shelf (210cm)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_16: THREE.Mesh;
  };
  materials: {
    SHL00005_Shelf: THREE.MeshStandardMaterial;
    SHL0005_Wood_C: THREE.MeshStandardMaterial;
    SHL0005_Wood_D: THREE.MeshStandardMaterial;
    SHL0005_Plastic_Gray: THREE.MeshStandardMaterial;
    SHL0005_Metal_Silver: THREE.MeshStandardMaterial;
    SHL0005_Drawers: THREE.MeshStandardMaterial;
  };
};

export function Shelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./models/shelf.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.146, 0.096, -0.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.SHL0005_Wood_C}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.SHL0005_Wood_D}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.SHL0005_Plastic_Gray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.SHL0005_Metal_Silver}
        />
      </group>
      <group position={[-0.744, 0.096, -0.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.SHL0005_Wood_C}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.SHL0005_Wood_D}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.SHL0005_Plastic_Gray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.SHL0005_Metal_Silver}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.SHL00005_Shelf}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.SHL0005_Drawers}
        position={[0.598, 0.017, 0.206]}
      />
    </group>
  );
}

useGLTF.preload("./models/shelf.glb");
