/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\vases.gltf --transform -t 
Files: .\vases.gltf [320.93KB] > C:\Users\tony\Documents\Github\configurator\public\models\vases-transformed.glb [28.35KB] (91%)
*/

import { Mesh, MeshStandardMaterial, Group, Texture } from "three";
import { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import useStore from "../state/store";

type GLTFResult = GLTF & {
  nodes: {
    vase_c: Mesh;
  };
  materials: {
    vase: MeshStandardMaterial;
  };
};

interface Pattern {
  [key: string]: Texture;
}

export function Vase(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("./models/vases.glb") as GLTFResult;
  const patterns: Pattern = useTexture({
    ink: "./textures/alcohol.jpg",
    zebra: "./textures/splatter.jpg",
    flowers: "./textures/flowers.jpg",
    orange: "./textures/orange.jpg",
    glass: "./textures/flowers.jpg",
  });
  const currentPattern = useStore((state) => state.currentPattern);
  const groupRef = useRef<Group>(null);

  const getCurrentPattern = () => {
    return patterns[currentPattern];
  };

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.vase_c.geometry}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.1}
      >
        {currentPattern === "glass" ? (
          <meshPhysicalMaterial
            color={0xffffff}
            transmission={1}
            opacity={1}
            metalness={0}
            ior={1.5}
            thickness={0.01}
            roughness={0}
            specularIntensity={1}
            specularColor={0xffffff}
            envMapIntensity={1}
            lightMapIntensity={1}
            transparent={true}
            map={getCurrentPattern()}
          />
        ) : (
          <meshStandardMaterial map={getCurrentPattern()} roughness={0} />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/vases.glb");

//"Wooden table" (https://skfb.ly/opQYN) by baneon is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).
// "Henrik Wool Rug 160x230cm, Mustard and Grey" (https://skfb.ly/6ywBR) by MADE.COM is licensed under Creative Commons Attribution-NonCommercial (http://creativecommons.org/licenses/by-nc/4.0/).
